services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4-arm64
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - elastic
    environment:
      - discovery.type=single-node
      - cluster.name=local-cluster
      - xpack.security.enabled=false
  kib:
    image: docker.elastic.co/kibana/kibana:8.13.4-arm64
    container_name: kib01
    ports:
      - "5601:5601"
    networks: 
      - elastic
    depends_on:
      - es
    environment:
      - ELASTICSEARCH_HOSTS="http://es01:9200" 

networks:
  elastic:
    driver: bridge
