services:
  es:
    image: custom/es:6.8.23-arm64
    container_name: es01
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - elastic
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  kib:
    image: docker.elastic.co/kibana/kibana:6.8.23
    container_name: kib01
    ports:
      - "5601:5601"
    networks: 
      - elastic
    depends_on:
      - es
    environment:
      - ELASTICSEARCH_HOSTS="http://es01:9200"

networks:
  elastic:
    driver: bridge
